package nuthatch.stratego.actions;

import nuthatch.library.Action;
import nuthatch.library.ActionBuilder;
import nuthatch.library.ActionFactory;
import nuthatch.library.FactoryFactory;
import nuthatch.library.MatchAction;
import nuthatch.library.MatchBuilder;
import nuthatch.library.Walk;
import nuthatch.pattern.Pattern;
import nuthatch.stratego.adapter.STermCursor;
import nuthatch.stratego.adapter.SWalker;

import org.spoofax.interpreter.terms.IStrategoTerm;

public class SActionFactory {
	public static final ActionFactory<IStrategoTerm, Integer, STermCursor, SWalker> factory = FactoryFactory.getActionFactory();


	public ActionFactory<IStrategoTerm, Integer, STermCursor, SWalker> getInstance() {
		return factory;
	}


	// The code below is generated by doing "Generate delegate methods" on 'factory', then putting 'static' in front of them.

	/**
	 * @param action
	 * @return
	 * @see nuthatch.library.impl.actions.StandardActionFactory#afterChild(nuthatch.library.Action)
	 */
	public static Action<SWalker> afterChild(Action<SWalker> action) {
		return factory.afterChild(action);
	}


	/**
	 * @param action
	 * @return
	 * @see nuthatch.library.impl.actions.StandardActionFactory#atLeaf(nuthatch.library.Action)
	 */
	public static Action<SWalker> atLeaf(Action<SWalker> action) {
		return factory.atLeaf(action);
	}


	/**
	 * @param action
	 * @return
	 * @see nuthatch.library.impl.actions.StandardActionFactory#atRoot(nuthatch.library.Action)
	 */
	public static Action<SWalker> atRoot(Action<SWalker> action) {
		return factory.atRoot(action);
	}


	/**
	 * @param action
	 * @return
	 * @see nuthatch.library.impl.actions.StandardActionFactory#beforeChild(nuthatch.library.Action)
	 */
	public static Action<SWalker> beforeChild(Action<SWalker> action) {
		return factory.beforeChild(action);
	}


	/**
	 * @param actions
	 * @return
	 * @see
	 *      nuthatch.library.impl.actions.ActionFactory#combine(nuthatch.walk.
	 *      Action
	 *      <W>[])
	 */
	@SafeVarargs
	public static final Action<SWalker> combine(Action<SWalker>... actions) {
		return factory.combine(actions);
	}


	/**
	 * @return
	 * @see nuthatch.library.impl.actions.StandardActionFactory#combineBuilder()
	 */
	public static ActionBuilder<SWalker> combineBuilder() {
		return factory.combineBuilder();
	}


	/**
	 * @param action
	 * @return
	 * @see nuthatch.library.impl.actions.StandardActionFactory#down(nuthatch.library.Action)
	 */
	public static Action<SWalker> down(Action<SWalker> action) {
		return factory.down(action);
	}


	/**
	 * @param downAction
	 * @param upAction
	 * @return
	 * @see nuthatch.library.impl.actions.StandardActionFactory#downup(nuthatch.library.Action,
	 *      nuthatch.library.Action)
	 */
	public static Action<SWalker> downup(Action<SWalker> downAction, Action<SWalker> upAction) {
		return factory.downup(downAction, upAction);
	}


	/**
	 * @param pat
	 * @param action
	 * @return
	 * @see nuthatch.library.impl.actions.StandardActionFactory#match(nuthatch.pattern.Pattern,
	 *      nuthatch.library.MatchAction)
	 */
	public static Action<SWalker> match(Pattern<IStrategoTerm, Integer> pat, MatchAction<IStrategoTerm, Integer, STermCursor, SWalker> action) {
		return factory.match(pat, action);
	}


	public static MatchBuilder<IStrategoTerm, Integer, STermCursor, SWalker> matchBuilder() {
		return factory.matchBuilder();
	}


	public static Action<SWalker> nop() {
		return factory.nop();
	}


	/**
	 * @param actions
	 * @return
	 * @see
	 *      nuthatch.library.impl.actions.ActionFactory#seq(nuthatch.walk.Action
	 *      <
	 *      W>[])
	 */
	@SafeVarargs
	public static final Action<SWalker> seq(Action<SWalker>... actions) {
		return factory.seq(actions);
	}


	/**
	 * @return
	 * @see nuthatch.library.impl.actions.StandardActionFactory#sequenceBuilder()
	 */
	public static ActionBuilder<SWalker> sequenceBuilder() {
		return factory.sequenceBuilder();
	}


	/**
	 * @param action
	 * @return
	 * @see nuthatch.library.impl.actions.StandardActionFactory#up(nuthatch.library.Action)
	 */
	public static Action<SWalker> up(Action<SWalker> action) {
		return factory.up(action);
	}


	/**
	 * @param action
	 * @return
	 * @see nuthatch.library.impl.actions.StandardActionFactory#walk(nuthatch.library.Action)
	 */
	public static Walk<SWalker> walk(Action<SWalker> action) {
		return factory.walk(action);
	}

}
